// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blog_categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlogCategories = `-- name: CreateBlogCategories :one
INSERT INTO blog_categories (
  name, status
) VALUES (
  $1, $2
)
RETURNING id, name, status, created_at
`

type CreateBlogCategoriesParams struct {
	Name   string
	Status pgtype.Bool
}

func (q *Queries) CreateBlogCategories(ctx context.Context, arg CreateBlogCategoriesParams) (BlogCategory, error) {
	row := q.db.QueryRow(ctx, createBlogCategories, arg.Name, arg.Status)
	var i BlogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlogCategories = `-- name: DeleteBlogCategories :exec
DELETE FROM blog_categories
WHERE id = $1
`

func (q *Queries) DeleteBlogCategories(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBlogCategories, id)
	return err
}

const getBlogCategories = `-- name: GetBlogCategories :one
SELECT id, name, status, created_at FROM blog_categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBlogCategories(ctx context.Context, id int64) (BlogCategory, error) {
	row := q.db.QueryRow(ctx, getBlogCategories, id)
	var i BlogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listBlogCategories = `-- name: ListBlogCategories :many
SELECT id, name, status, created_at FROM blog_categories
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListBlogCategoriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBlogCategories(ctx context.Context, arg ListBlogCategoriesParams) ([]BlogCategory, error) {
	rows, err := q.db.Query(ctx, listBlogCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogCategory
	for rows.Next() {
		var i BlogCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogCategories = `-- name: UpdateBlogCategories :exec
UPDATE blog_categories
SET 
  name = $2,
  status = $3
WHERE id = $1
`

type UpdateBlogCategoriesParams struct {
	ID     int64
	Name   string
	Status pgtype.Bool
}

func (q *Queries) UpdateBlogCategories(ctx context.Context, arg UpdateBlogCategoriesParams) error {
	_, err := q.db.Exec(ctx, updateBlogCategories, arg.ID, arg.Name, arg.Status)
	return err
}
