// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blog.sql

package db

import (
	"context"
)

const createBlogs = `-- name: CreateBlogs :one
INSERT INTO blogs (
  title, description_article, category_id, account_id
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, title, description_article, category_id, account_id, created_at
`

type CreateBlogsParams struct {
	Title              string
	DescriptionArticle string
	CategoryID         int64
	AccountID          int64
}

func (q *Queries) CreateBlogs(ctx context.Context, arg CreateBlogsParams) (Blog, error) {
	row := q.db.QueryRow(ctx, createBlogs,
		arg.Title,
		arg.DescriptionArticle,
		arg.CategoryID,
		arg.AccountID,
	)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DescriptionArticle,
		&i.CategoryID,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlogs = `-- name: DeleteBlogs :exec
DELETE FROM blogs
WHERE id = $1
`

func (q *Queries) DeleteBlogs(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBlogs, id)
	return err
}

const getBlogs = `-- name: GetBlogs :one
SELECT id, title, description_article, category_id, account_id, created_at FROM blogs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBlogs(ctx context.Context, id int64) (Blog, error) {
	row := q.db.QueryRow(ctx, getBlogs, id)
	var i Blog
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.DescriptionArticle,
		&i.CategoryID,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}

const listBlogss = `-- name: ListBlogss :many
SELECT id, title, description_article, category_id, account_id, created_at FROM blogs
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListBlogssParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListBlogss(ctx context.Context, arg ListBlogssParams) ([]Blog, error) {
	rows, err := q.db.Query(ctx, listBlogss, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blog
	for rows.Next() {
		var i Blog
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.DescriptionArticle,
			&i.CategoryID,
			&i.AccountID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogs = `-- name: UpdateBlogs :exec
UPDATE blogs
SET 
  title = $2,
  description_article = $3,
  category_id = $4,
  account_id = $5
WHERE id = $1
`

type UpdateBlogsParams struct {
	ID                 int64
	Title              string
	DescriptionArticle string
	CategoryID         int64
	AccountID          int64
}

func (q *Queries) UpdateBlogs(ctx context.Context, arg UpdateBlogsParams) error {
	_, err := q.db.Exec(ctx, updateBlogs,
		arg.ID,
		arg.Title,
		arg.DescriptionArticle,
		arg.CategoryID,
		arg.AccountID,
	)
	return err
}
