// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID             int64
	Owner          string
	Balance        int64
	ProfilePicture pgtype.Text
	Currency       string
	CreatedAt      pgtype.Timestamptz
}

type Blog struct {
	ID                 int64
	Title              string
	DescriptionArticle string
	CategoryID         int64
	AccountID          int64
	BannerImage        pgtype.Text
	CreatedAt          pgtype.Timestamptz
}

type BlogCategory struct {
	ID        int64
	Name      string
	Status    pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type Entry struct {
	ID        int64
	AccountID int64
	// Can be negative or positive value
	Amount    int64
	CreatedAt pgtype.Timestamptz
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	// Must be positive
	Amount    int64
	CreatedAt pgtype.Timestamptz
}
