// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: refresh_token.sql

package db

import (
	"context"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_token (
  account_id, token_refresh
) VALUES (
  $1, $2
)
RETURNING id, account_id, token_refresh, created_at
`

type CreateRefreshTokenParams struct {
	AccountID    int64
	TokenRefresh string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.AccountID, arg.TokenRefresh)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenRefresh,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_token
WHERE account_id = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, accountID int64) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, accountID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, account_id, token_refresh, created_at FROM refresh_token
WHERE account_id = $1 LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, accountID int64) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, accountID)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.TokenRefresh,
		&i.CreatedAt,
	)
	return i, err
}
